swagger: "2.0"
info:
  description: |
    This API provides access to NIT Hamirpur result. Contributions are welcome.
    
    **gzip** compression is supported. [Learn more](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)
  version: "0.2.0"
  title: NITH Result API (Beta)
produces:
  - application/json
consumes:
  - application/json

basePath: /api/result

# Paths supported by the server application
paths:
  /student:
    get:
      operationId: nith_result_api.read_all
      tags:
        - Student
      summary: Read the entire list of students.
      description: |
        Returns object containing list of students inside data. Students 
        can be filtered on basis of various parameters. Each student 
        has to satisfy all parameters 
        i.e. multiple parameters are connected by `AND` operation. 
        
        `link` contains hyperlink to student's complete result.

        If there are more pages, `next` will be present, and if there are 
        previous pages then `previous` key will be present. `pagination` 
        is always present. `previous` and `next` are hyperlinks.
      parameters:
        - name: name
          in: query
          description: > 
            Response will contain those students whose name have 
            stated string in them. Matching is case insensitive.
          required: false
          type: string
        - name: roll
          in: query
          description: >
            Response will contain those students whose roll number matches 
            stated SQL pattern. % and _ SQL wildcards supported. Matching is case insensitive.
          required: false
          type: string
        - name: branch
          in: query
          description: >
            Response will contain those students whose branch is as stated. 
            Matching is exact and case insensitive.
          required: false
          type: string
        - name: subject_code
          in: query
          description: >
            Response will contain those students who have taken subject 
            with stated SQL pattern. Matching is case insensitive.
          required: false
          type: string
        - name: min_cgpi
          in: query
          description: >
            Latest cgpi of the student in response is greater than  or equal to this value.
          required: false
          type: number
          format: float
          default: 0
        - name: max_cgpi
          in: query
          description: >
            Latest cgpi of the student in response is less than or equal to this value.
          required: false
          type: number
          format: float
          default: 10
        - name: min_sgpi
          in: query
          description: >
            Latest sgpi of the student in response is greater than or equal to this value.
          required: false
          type: number
          format: float
          default: 0
        - name: max_sgpi
          in: query
          description: >
            Latest sgpi of the student in response is less than or equal to this value.
          required: false
          type: number
          format: float
          default: 10
      responses:  
        200:
          description: Successfully read students.
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  properties:
                    name:
                      type: string
                    roll:
                      type: string
                    branch:
                      type: string
                    cgpi:
                      type: string
                    sgpi:
                      type: string
                    link:
                      type: string
              pagination:
                type: object
                properties:
                  "previous":
                    type: string
                  "next":
                    type: string

  /student/{roll}:
    get:
      operationId: nith_result_api.read
      tags:
        - Student
      summary: Get complete result of single student.
      description: |
        Get complete result of single student. `cgpi` and `sgpi` are latest one. 
        
        `rank` contains rank of student.
        Rank can be on `college`, `year` and `class` level and criteria used are two viz. `cgpi` and `sgpi`.
      parameters:
        - name: roll
          in: path
          description: Roll number of the student whose result is to get
          type: string
          required: True
      responses:
        200:
          description: Successfully read result of the student
          schema:
            $ref: '#/definitions/Student'
        404:
          description: Roll number not found
          schema:
            type: object
            properties:
              status:
                type: string

  /subject:
    get:
      operationId: nith_result_api.read_subjects
      tags:
        - Subject
      summary: Read the entire list of subjects
      description: Read the list of subjects
      responses:
        200:
          description: Successfully read subject list
          schema:
            type: array
            items:
              properties:
                "sub_point":
                  type: integer
                "subject":
                  type: "string"
                "subject_code":
                  type: "string"
definitions:
  Student:
    type: object
    properties:
      name:
        type: string
      roll:
        type: string
      branch:
        type: string
      cgpi:
        type: number
        format: float
      sgpi:
        type: number
        format: float
      rank:
        type: object
        properties:
          college:
            type: object
            properties:
              cgpi:
                type: string
              sgpi:
                type: string
          year:
            type: object
            properties:
              cgpi:
                type: string
              sgpi:
                type: string
          class:
            type: object
            properties:
              cgpi:
                type: string
              sgpi:
                type: string
      result:
        type: array
        items:
          $ref: '#/definitions/Subject'
      summary:
        type: array
        items:
          properties:
            cgpi:
              type: string
            cgpi_total:
              type: string
            sgpi:
              type: string
            sgpi_total:
              type: string
            sem:
              type: string 
            
  Subject:
    type: object
    properties:
      grade:
        type: string
      sub_gp:
        type: string
      sub_point:
        type: string
      subject:
        type: string
      subject_code:
        type: string
      sem:
        type: string