swagger: "2.0"
info:
  description: This API provides access to result. Do not use this api yet.
  version: "0.1.0"
  title: NITH Result API (Experimental)
consumes:
  - application/json
produces:
  - application/json

basePath: /api/result

# Paths supported by the server application
paths:
  /students:
    get:
      operationId: nith_result_api.read_all
      tags:
        - Student
      summary: Read the entire list of student
      description: Read the list of student
      responses:  
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                roll:
                  type: string
                branch:
                  type: string
                cgpi:
                  type: string
                sgpi:
                  type: string
                link:
                  type: string
  
  /student/{roll}:
    get:
      operationId: nith_result_api.read
      tags:
        - Student
      summary: Read one person from the people list
      description: Read one person from the people list
      parameters:
        - name: roll
          in: path
          description: Roll number of student whose result is to get
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            $ref: '#/definitions/Student'

definitions:
  Student:
    type: object
    properties:
      name:
        type: string
      roll:
        type: string
      branch:
        type: string
      cgpi:
        type: string
      sgpi:
        type: string
      rank:
        type: object
      result:
        type: array
        items:
          $ref: '#/definitions/Subject'
      summary:
        type: array
        items:
          properties:
            cgpi:
              type: string
            cgpi total:
              type: string
            sgpi:
              type: string
            sgpi total:
              type: string
            sem:
              type: string 
  Subject:
    type: object
    properties:
      grade:
        type: string
      sub gp:
        type: string
      sub point:
        type: string
      subject:
        type: string
      subject code:
        type: string
      sem:
        type: string